version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Oslo"
    commit-message:
      include: scope
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Oslo"
    commit-message:
      include: scope
      prefix: "ci"
