global using FluentAssertions;
global using NetArchTest.Rules;
global using Saga.Tyr.Domain;
global using Saga.Tyr.Application;
global using Saga.Tyr.Host;
global using Saga.Tyr.Infrastructure;
global using Saga.Tyr.Presentation;
global using System.Reflection;
global using Xunit;