global using FluentAssertions;
global using NetArchTest.Rules;
global using Saga.Dagny.Domain;
global using Saga.Dagny.Application;
global using Saga.Dagny.Host;
global using Saga.Dagny.Infrastructure;
global using Saga.Dagny.Presentation;
global using System.Reflection;
global using Xunit;