global using FluentAssertions;
global using NetArchTest.Rules;
global using Saga.Gudrun.Domain;
global using Saga.Gudrun.Application;
global using Saga.Gudrun.Host;
global using Saga.Gudrun.Infrastructure;
global using Saga.Gudrun.Presentation;
global using System.Reflection;
global using Xunit;