global using FluentAssertions;
global using NetArchTest.Rules;
global using Saga.Vidar.Domain;
global using Saga.Vidar.Application;
global using Saga.Vidar.Host;
global using Saga.Vidar.Infrastructure;
global using Saga.Vidar.Presentation;
global using System.Reflection;
global using Xunit;